Issue#70
warriordog/ActivityPubSharp pull request #76
Opened 2023-08-01 13:10 UTC by viktoriussuwandi

fix #70

Hi [warriordog](https://github.com/warriordog),
This is my PR  for this issue, please check it out

2023-08-01 15:36 UTC, warriordog commented
@viktoriussuwandi Hello, thank you for the PR! Are some of the changes missing? Many of the types are not updated, and the renamed `APTypeAttribute` class isn't in any of the commits.

2023-08-01 15:53 UTC, viktoriussuwandi commented
no worries @warriordog, I'll do it step by step untill all files covered, thanks for your advice :)

2023-08-12 04:11 UTC, viktoriussuwandi commented
Hi @warriordog, I think it is ready to review, just lemme know if there is still need to be updated

2023-08-14 15:52 UTC, warriordog commented
@viktoriussuwandi thank you! Reviewing now

2023-08-14 15:55 UTC, warriordog requested changes
I left a couple of comments. Also, this needs to be rebased onto the latest changes. There's a lot of them, so please let me know if you'd like help with that!

2023-08-14 15:55 UTC, warriordog commented on ActivityPub.Types/Json/ASTypeKeyAttribute.cs
> +public sealed class ASTypeAttribute : Attribute
Shouldn't this be `APTypeAttribute`?

2023-08-15 01:08 UTC, viktoriussuwandi commented on ActivityPub.Types/Json/ASTypeKeyAttribute.cs
> +public sealed class ASTypeAttribute : Attribute
Already updated @warriordog

2023-08-15 01:14 UTC, viktoriussuwandi commented on ActivityPub.Types/Json/ASTypeKeyAttribute.cs
already renamed the file @warriordog

2023-08-16 21:11 UTC, warriordog commented
@viktoriussuwandi this looks good now, just needs a rebase. I can do that part myself, if you'd like. Just let me know

2023-08-17 02:18 UTC, viktoriussuwandi commented
Thanks for the opportunity @warriordog, I leave the rest (rebase part) for you :)

2023-08-17 03:33 UTC, warriordog commented
Merged in #107, for technical reasons

2023-08-17 03:33 UTC, closed without merging